version: "3.3"

services:
  backend:
    image: thedumdum/backend:latest
    container_name: backend
    ports:
      - 80:80
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.services.app.loadbalancer.server.port=80
      - traefik.http.services.app.http.entrypoints=http
      - traefik.http.routers.app.http.rule=Host(`api.thedumdum.com`)
      - traefik.docker.network=traefik.public
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
