version: "3.3"

services:
  traefik:
    container_name: traefik
    image: "traefik:latest"
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-public-certificates:/certificates
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.le.acme.email=orca-per-0l@icloud.com
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --log
      - --accesslog

    networks:
      - traefik-public

volumes: traefic-public-certificates

networks:
  traefik-public:
    external: true
