version: "3.3"

services:
  traefik:
    container_name: traefik
    image: "traefik:latest"
    ports:
      - "80:80"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
      - --entrypoints.http.address=:80
      - --providers.docker
      - --providers.exposebydefault=false
      - --log
      - --accesslog

    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
