version: "3.3"

services:
  backend:
    image: thedumdum/backend:latest
    container_name: backend
    ports:
      - 80:80
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.services.BACKEND_APP.loadbalancer.server.port=80
      - traefik.http.routers.BACKEND_APP.rule=Host(`api.thedumdum.com`)
      - traefik.docker.network=traefik.public
    networks:
      - traefik-public
