version: "3.3"

services:

  portal:
    image: thedumdum/frontend:latest
    container_name: portal-frontend
    networks:
    - thedumdum
    - gateway

    ports:
      - "3000:80"

  backend:
    image: thedumdum/backend:latest
    container_name: portal-backend
    networks:
    - thedumdum
    - gateway

networks:
  - gateway
  - thedumdum
